//Apropo Page
export const Aporo_title = 'A Propos de Planet';
export const Apropos_Paragraphe = `PlanetConectUs est l'un des principaux fournisseurs 7e solutions IOT. Nous donnons aux entreprises les moyens de se connecter et d'évoluer efficacement en leur permettant de fournir des solutions innovantes alimentées par l'IOT. Notre développement d'applications IOT permet aux entreprises de combler le fossé entre le monde réel et le monde numérique grâce à une toute nouvelle expérience.Nous sommes fiers d'avoir l'un des objets connectés les plus rapides et sécurisés au monde et certains des meilleurs ingénieurs de services IOT parmi nos talentueux. équipe de développement qui se concentre sur la conception et le développement innovants. Les services de l'Internet des objets permettent aux entreprises de réussir en transformant leurs processus métier, leur infrastructure réseau et leurs modèles opérationnels. Notre équipe d'experts a travaillé sur de nombreux projets liés à l'IOT, développant des solutions Internet des objets de bout en bout. L'ensemble des services proposés par PlanetConectUs comprend la consultation, le développement et l'intégration de services IOT.`;

//Partenaire Page
export const Partenaire_title = 'PARTENAIRES';
export const Partenaire_Paragraphe = `On ne peut pas innover sans faire de la recherche et développement, c'est pourquoi planet conectus dispose d'un pôle R&D composé d'ingénieurs ayant une expérience globale et maîtrisant les dernières technologies.Notre entreprise est basée sur la fabrication et la rénovation dans le domaine de l'IOT. Nous avons résolu le problème de la traingulation par Bleutooth d'un smartphone à l'intérieur d'une voiture qui roule à 30 km / h pour une société de péage. Nous sommes parvenus à résoudre un problème jamais résolu dans le monde après un an de recherche et développement. ce nom de solution Paygate solution .Planet connectus Voulez-vous être votre partenaire? Tout ce que vous avez à faire est de déterminer si vous souhaitez ou non établir une base pour une croissance mutuelle des revenus. Si oui, pourquoi attendre? Contactez-nous aujourd'hui.`;

//Platforme Page
export const Platforme_title = 'PLATFORME DE PLANET';
export const Platforme_Paragraphe = `Les plateformes Planet Conectus sont le compagnon idéal des innovateurs du monde de l'IoT. Ces Applications permettent aux clients de comprendre facilement les tâches des productions d'un objet connecté, notre paygate a besoin des applications de paltform pour nous donne un bon résultat .La plateforme Planet conectus vous donnera la possibilité de gérer:`;
